# Generated by Django 2.0.9 on 2019-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181127_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gift',
            field=models.BooleanField(default=False),
        ),
    ]
