# Generated by Django 2.1.7 on 2019-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_customer_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_read',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
