# Generated by Django 2.1.2 on 2018-10-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181030_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
