# Generated by Django 2.1.2 on 2018-10-30 15:38

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postpage_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='excerpt',
            field=wagtailmd.utils.MarkdownField(default='test'),
            preserve_default=False,
        ),
    ]
