# Generated by Django 2.1.2 on 2018-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postpage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='header_image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
